import * as THREE from 'three';
import {analyze,estimate,estimateVolume,UNITS,unitChoices,suggestImportUnit,cloneCard,positive} from './core.mjs';
import {parseModel,exportModel,flatten} from './formats.mjs';
import {createViewer} from './viewer.mjs';
import {readWorkspace,writeWorkspace} from './storage.mjs';
import {parseHistory,summary} from './market.mjs';
import prices from './prices.json';
import {runWorker} from './worker-client.mjs';
import {fingerprint,validateSummary,exportLarge} from './large-model.mjs';
import {feeCatalog,feeModes,makeFee,validateFees,calculateFees} from './fees.mjs';
import {calculateQuote,processTemplates,applyProcessTemplate} from './quote.mjs';
import {buildSampleSheetBatchPdf,buildSampleSheetJpegs,sampleSheetFileName} from './pdf.mjs';
import {zipFiles} from './archive.mjs';
import {serializeProject,parseProject} from './project.mjs';
import {initLanguage} from './i18n.mjs';
import {materials,otherMetalKeys} from './materials.mjs';
import {removeUntouchedLegacyCube} from './legacy-demo.mjs';
import {currencies,CURRENCY_SNAPSHOT_DATE,formatCurrency,toCanonicalCny,toDisplayCurrency} from './currency.mjs';
import {DISPLAY_UNITS as displayUnits,defaultCurrencyForLocale,lengthFromMillimeters,lengthToMillimeters} from './preferences.mjs';
const sourceFiles=new Map();let activeJob=null,persistenceBlocked=false,browserProjectStem='',browserSaveSequence=0;
const collapsedModels=new Set();
let activeLocale='zh-CN',activeCurrency='CNY',displayUnit='mm';
function progress(fraction,label){$('busyText').textContent=label;if(fraction===null)$('computeProgress').removeAttribute('value');else $('computeProgress').value=fraction;}
function startJob(payload){activeJob=runWorker(payload,progress);$('cancelBtn').disabled=false;return activeJob.promise;}

const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(n,d=3)=>Number.isFinite(n)?n.toLocaleString(({en:'en-US',ja:'ja-JP',ko:'ko-KR'}[activeLocale]??activeLocale),{maximumFractionDigits:d,minimumFractionDigits:Math.abs(n)<.001&&n!==0?0:undefined}):'—';
const money=n=>n===null?language.translate('待填写单价'):formatCurrency(n,activeCurrency,activeLocale);
let state={version:1,models:[],cards:[],selected:null,histories:{}},viewer,saveTimer,toastTimer,busy=false;
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),5000);}
function selected(){return state.cards.find(c=>c.id===state.selected);}
function modelFor(c=selected()){return state.models.find(m=>m.id===c?.modelId);}
function history(metal){return state.histories[metal]||prices[metal]||{rows:[],source:'自定义材质，请输入实际采购价',kind:'用户定义'};}
function defaultPrice(metal){return summary(history(metal).rows)?.mean??null;}
function origin(metal){const s=summary(history(metal).rows);return s?`${state.histories[metal]?'用户行情':'参考快照'} · ${s.start} — ${s.end} · ${s.count} 个交易日均值`:'手动单价（未填写）';}
function unitName(unit){return {mm:'毫米',cm:'厘米',m:'米',in:'英寸',ft:'英尺'}[unit]??unit;}
function displayDimensions(dimensions,factors,scales){return dimensions.map((n,i)=>fmt(lengthFromMillimeters(n*factors[i]*scales[i],displayUnit),2)).join(' × ');}
function thumbnailFor(model){try{return viewer?.makeThumbnail(model,materials.gold.color)??null;}catch(error){console.warn('缩略图生成失败',error);return null;}}
function safeThumbnail(value){return typeof value==='string'&&value.length<40000&&/^data:image\/webp;base64,[A-Za-z0-9+/=]+$/.test(value)?value:null;}
function makeCard(m,original=true){return {id:crypto.randomUUID(),modelId:m.id,name:original?'原始尺寸':'计算副本',original,unit:m.defaultUnit,scale:[1,1,1],metal:'gold',density:materials.gold.density,price:defaultPrice('gold'),priceOrigin:origin('gold'),priceBasis:'unconfirmed',supplierName:'',quoteDate:'',validUntil:'',feedAllowancePercent:null,materialBasis:'net',batchQuantity:1,processTemplate:'',fees:[]};}
function result(c){const m=modelFor(c);if(m?.manual)return c.manualVolume===null?null:estimateVolume(c.manualVolume,c.density,c.price);if(!m?.analysis.valid)return null;return estimate(m.analysis.volume,UNITS[c.unit],c.scale,c.density,c.price);}
function quote(c){return calculateQuote(c,modelFor(c),result(c));}
function save(){clearTimeout(saveTimer);if(persistenceBlocked){$('saveStatus').textContent='原有记录无法恢复，暂不覆盖；请打开文件或在更多中重新开始';return;}$('saveStatus').textContent='正在保存…';saveTimer=setTimeout(async()=>{try{await writeWorkspace(state);$('saveStatus').textContent='已自动保存到此浏览器';}catch{$('saveStatus').textContent='浏览器无法保存，请使用「保存文件」';}},300);}
function update(fit=false){render();if(fit)viewer?.fit();save();}
function selectCard(id){state.selected=id;update(true);$('propertiesBody').scrollTop=0;}
function render(){
 const c=selected(),m=modelFor(c);$('modelCount').textContent=state.models.length;$('cardCount').textContent=state.cards.length;
 $('modelList').innerHTML=state.models.map(mod=>{const records=state.cards.filter(card=>card.modelId===mod.id),collapsed=collapsedModels.has(mod.id);return `<div class="model-group ${m?.id===mod.id?'active':''}"><div class="model-item"><button class="model-group-toggle" data-toggle-model="${esc(mod.id)}" aria-expanded="${!collapsed}" aria-label="${collapsed?'展开':'折叠'} ${esc(mod.name)}">${collapsed?'▸':'▾'}</button><button class="model-select" data-model="${esc(mod.id)}"><span class="model-thumbnail">${mod.thumbnail?`<img src="${esc(mod.thumbnail)}" alt="">`:`<span>${mod.manual?'cm³':'◇'}</span>`}</span><span class="model-label"><strong>${esc(mod.name)}</strong><small>${mod.manual?'体积计算 · 无模型':esc(mod.ext.toUpperCase())+' · '+fmt(mod.analysis.triangles,0)+' 面'} · ${records.length} 份记录</small></span></button><button class="delete-model" data-remove-model="${esc(mod.id)}" title="删除此模型与关联记录" aria-label="删除 ${esc(mod.name)}">×</button></div><div class="model-group-children" ${collapsed?'hidden':''}>${records.map(card=>`<button class="model-record ${card.id===state.selected?'active':''}" data-select-card="${esc(card.id)}"><span>└</span>${esc(card.name)}<small>${card.manualVolume===null&&mod.manual?'待输入':result(card)?fmt(result(card).mass)+' g':'待核对'}</small></button>`).join('')}</div></div>`;}).join('');
 $('cardList').innerHTML=state.cards.map(card=>{const r=result(card),q=quote(card),mod=modelFor(card);return `<article class="calc-card ${card.id===state.selected?'active':''}" data-card="${esc(card.id)}" tabindex="0" role="button" aria-label="选择 ${esc(card.name)}"><div class="card-top"><strong>${esc(card.name)}</strong><div class="card-actions"><button data-duplicate="${esc(card.id)}" title="复制计算记录" aria-label="复制 ${esc(card.name)}">⧉</button>${card.original&&!mod.manual?'':`<button data-delete="${esc(card.id)}" title="删除记录" aria-label="删除 ${esc(card.name)}">×</button>`}</div></div><div class="card-mass">${r?fmt(r.mass):'—'}<small>g</small></div><div class="card-detail"><span>${esc(materials[card.metal].symbol)} · ${mod.manual?'手动体积':card.original?'<span class="orig-tag">原始</span>':fmt(card.scale[0]*100,1)+'%'}</span><span>${q.materialCost===null?'待估算':money(q.materialCost)}</span></div><div class="micro" style="margin-top:7px;letter-spacing:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${esc(mod.name)}</div></article>`;}).join('')||'<div class="empty-record">导入模型，即可创建第一份计算记录。</div>';
 $('propertiesBody').hidden=!c;$('noSelection').hidden=!!c;for(const id of ['addCardBtn','copyBtn','exportBtn','marketBtn','addFeeBtn','sheetBtn'])$(id).disabled=!c;
 $('previewUpgrade').hidden=!(m?.previewOnly&&m.analysis.triangles<=2000000&&m.positions.length/9<m.analysis.triangles);
 $('manualCanvasHelp').hidden=!m?.manual;$('viewport').classList.toggle('manual-mode',!!m?.manual);$('sizeDetails').hidden=!!m?.manual;$('manualBtn').classList.toggle('selected',!!m?.manual);
 if(!c||!m){$('viewName').textContent='等待导入模型';$('viewSub').textContent='拖入模型，或点击右上角导入';$('meshBadge').textContent='本地处理 · 文件不会上传';$('feeList').innerHTML='';$('costSummary').textContent='未添加';$('makingCost').textContent=money(0);$('grandTotal').textContent='—';$('batchTotal').textContent='—';$('foldedBatchTotal').textContent='—';$('foldedMass').textContent='— g';$('comparisonTable').innerHTML='';viewer?.clear();return;}
 $('viewName').textContent=m.manual?'体积计算':m.name;$('viewSub').textContent=`${c.name} · ${unitName(c.unit)}读取${m.ext==='stl'?'（STL 默认毫米，可修改）':''}`;
 const a=m.analysis;
 const previewState=m.previewOnly?(m.positions.length/9===a.triangles?'完整表面预览 / 完整体积计算':'抽样预览 / 完整体积计算'):a.topologyChecked===false?'完整计算 / 未检查封闭性':a.valid?'边拓扑通过 · 未检查自相交':'几何需核对';
 const inspection=a.topologyChecked===false?`未检查封闭性与自相交 · 退化面 ${fmt(a.degenerate,0)} · 请确认网格封闭且朝向一致`:a.valid?'':`边界边 ${fmt(a.boundary,0)} · 非流形边 ${fmt(a.nonManifold,0)} · 朝向冲突 ${fmt(a.inconsistent,0)} · 退化面 ${fmt(a.degenerate,0)}`;
 $('meshBadge').textContent=`${fmt(a.triangles,0)} 面 · ${previewState}${inspection?' · '+inspection:''}`;
 $('cardName').value=language.translate(c.name);$('recordMeta').textContent=m.manual?'独立的手动体积记录 · 不关联三维模型':c.original?'原始尺寸记录 · 复制后可调整比例':'独立计算副本 · 不改变原模型';
 const r=result(c),q=quote(c),feeResult={lines:q.fees,making:q.makingCost,total:q.unitTotal};$('mass').textContent=r?fmt(r.mass):'—';$('foldedMass').textContent=(r?fmt(r.mass):'—')+' g';$('volume').textContent=r?fmt(r.volume,6):'—';$('feedMass').textContent=q.feedMass===null?'待填写余量':fmt(q.feedMass)+' g';$('feedAllowance').value=c.feedAllowancePercent??'';$('materialBasis').value=c.materialBasis??'net';$('cost').textContent=q.materialCost===null?m.manual?'待输入体积或余量':'待填写单价或余量':money(q.materialCost);$('quoteConfidence').textContent=`报价依据：${q.confidence} · ${q.confidence==='已检查'?'边拓扑已检查；仍须人工确认自相交与重叠壳体':q.confidence==='未完整检查'?'超过 15 万面，未做完整边拓扑检查；需人工确认封闭与朝向':'几何或手动体积需人工确认'}`;
 $('feeList').innerHTML=feeResult.lines.map(f=>`<div class="fee-row" data-fee-id="${esc(f.id)}"><div class="fee-row-top"><input data-fee-field="name" aria-label="费用名称" maxlength="80" value="${esc(language.translate(f.name))}"><button data-remove-fee="${esc(f.id)}" title="删除该费用" aria-label="删除 ${esc(f.name)}">×</button></div><div class="fee-row-fields"><select data-fee-field="mode" aria-label="计价方式">${Object.entries(feeModes).map(([k,v])=>`<option value="${k}" ${k===f.mode?'selected':''}>${v}</option>`).join('')}</select><input data-fee-field="rate" type="number" min="0" step="any" placeholder="单价" aria-label="费用单价" value="${f.rate===null?'':Number(toDisplayCurrency(f.rate,activeCurrency).toPrecision(7))}">${f.mode==='perUnit'?`<input data-fee-field="quantity" type="number" min="0.001" step="any" aria-label="数量" value="${f.quantity}">`:''}</div><small>${f.amount===null?'待填写':'小计 '+money(f.amount)}</small></div>`).join('')||'<p class="hint">尚未添加制作费用。</p>';
 $('costSummary').textContent=(c.fees??[]).length?feeResult.making===null?'待计算':money(feeResult.making):'未添加';$('makingCost').textContent=feeResult.making===null?'待计算':money(feeResult.making);$('grandTotal').textContent=feeResult.total===null?'待计算':money(feeResult.total);$('batchTotal').textContent=q.batchTotal===null?'待计算':money(q.batchTotal);$('foldedBatchTotal').textContent=$('batchTotal').textContent;$('batchQuantity').value=q.batchQuantity;$('pendingFees').textContent=q.pendingFees.length?`${q.pendingFees.length} 项工艺单价待厂家报价，未计入当前金额。`:'已填写的工艺项目均已计入。';$('processTemplate').value=c.processTemplate??'';$('addFeeBtn').disabled=(c.fees??[]).length>=30;
 $('volumeLabel').textContent=m.manual?'输入体积':'模型体积';$('volumeLock').disabled=!m.manual;$('volumeLock').textContent=c.volumeLocked!==false?'锁定 🔒':'已解锁';$('volumeLock').setAttribute('aria-label',c.volumeLocked!==false?'解锁体积输入':'锁定体积输入');$('volumeLock').title=m.manual?'点击锁定或解锁体积':'模型体积自动计算，不可手动更改';$('volumeInput').hidden=!m.manual;$('volumeInput').disabled=!m.manual||c.volumeLocked!==false;$('volumeInput').value=m.manual?(c.manualVolume??''):'';$('volume').hidden=!!m.manual;$('volumeHint').textContent=m.manual?'单位为 cm³（立方厘米）。1 cm³ = 1,000 mm³。':'由模型自动计算；只知道体积时，选择上方「输入体积」。';
 $('unit').value=c.unit;['dimX','dimY','dimZ'].forEach((id,i)=>{const n=lengthFromMillimeters(a.dimensions[i]*UNITS[c.unit]*c.scale[i],displayUnit);$(id).value=n<.00001?Number(n.toPrecision(5)):Number(n.toFixed(5));$(id).disabled=c.original||a.dimensions[i]===0;});document.querySelectorAll('.size-unit').forEach(el=>el.textContent=displayUnit);
 $('scalePercent').value=Number((c.scale[0]*100).toPrecision(8));$('scalePercent').disabled=c.original;$('lockRatio').disabled=c.original;
 $('scaleHelp').textContent=c.original?'原始尺寸已锁定。先复制，再尝试新的大小。':'修改单轴尺寸可锁定比例；整体百分比会重设为等比缩放。';
 document.querySelectorAll('[data-metal]').forEach(b=>b.classList.toggle('active',b.dataset.metal===c.metal));$('otherMetalsBtn').classList.toggle('active',otherMetalKeys.includes(c.metal));$('otherMetalsBtn').querySelector('small').textContent=otherMetalKeys.includes(c.metal)?materials[c.metal].name:'其他金属';$('density').value=c.density;$('price').value=c.price===null?'':Number(toDisplayCurrency(c.price,activeCurrency).toFixed(6));$('priceCurrency').textContent=activeCurrency+' / g';$('priceOrigin').textContent=c.priceOrigin;$('priceBasis').value=c.priceBasis??'unconfirmed';$('supplierFields').hidden=c.priceBasis!=='supplier';$('supplierName').value=c.supplierName??'';$('quoteDate').value=c.quoteDate??'';$('validUntil').value=c.validUntil??'';$('quoteReadiness').textContent=q.priceReady?c.priceBasis==='supplier'?'厂家报价资料已填写；请核对有效期。':'已明确采用带日期的离线参考价；正式采购前仍需确认。':'当前仅为参考估算：请选择参考价，或填写完整厂家报价与日期。';
 const related=state.cards.filter(x=>x.modelId===m.id);$('comparisonTable').innerHTML=`<table><thead><tr><th>比较项目</th>${related.map(x=>`<th>${esc(x.name)}</th>`).join('')}</tr></thead><tbody>${[[language.translate('外形尺寸')+' '+displayUnit,x=>m.manual?'—':m.analysis.dimensions.map((n,i)=>fmt(lengthFromMillimeters(n*UNITS[x.unit]*x.scale[i],displayUnit),2)).join(' × ')],['体积 cm³',x=>fmt(quote(x).volume,4)],['理论净重 g',x=>fmt(quote(x).netMass)],['投料量 g',x=>quote(x).feedMass===null?'待确认':fmt(quote(x).feedMass)],['单件材料费',x=>money(quote(x).materialCost)],['单件制作费',x=>money(quote(x).makingCost)],['单件合计',x=>money(quote(x).unitTotal)],['数量 / 整批',x=>`${quote(x).batchQuantity} / ${money(quote(x).batchTotal)}`],['几何可信度',x=>quote(x).confidence]].map(([label,value])=>`<tr><th>${label}</th>${related.map(x=>`<td>${esc(value(x))}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
 $('exportNote').textContent=m.previewOnly?'此记录保存预览和完整计算结果。导出将重新读取完整原文件。':'';
 $('relinkBtn').hidden=!m.previewOnly||sourceFiles.has(m.id);$('exportBtn').disabled=!!m.manual;if(m.manual)$('exportNote').textContent='手动体积记录没有三维几何，不能导出模型。';
 if(m.manual){viewer?.clear();$('meshBadge').textContent='手动输入 · 不创建或修改三维模型';$('viewSub').textContent=c.name;}else viewer?.setModel(m,c.scale.map(n=>n*UNITS[c.unit]),materials[c.metal].color);
}
async function withBusy(message,task){if(busy)return;busy=true;activeJob=null;$('cancelBtn').disabled=true;$('computeProgress').removeAttribute('value');$('busyText').textContent=message;$('busy').hidden=false;await new Promise(r=>setTimeout(r,50));try{return await task();}catch(e){console.error(e);toast(e.message||'操作失败，请检查文件');}finally{busy=false;activeJob=null;$('busy').hidden=true;}}
async function chooseUnit(name,dimensions,ext){
 const suggestion=suggestImportUnit(ext,dimensions);$('unitExplanation').textContent=`「${name}」需要确认尺寸单位。根据格式预选 ${unitName(suggestion)}；请选择与你建模软件中的真实尺寸相符的单位。`;
 const choices=unitChoices(dimensions);
 $('unitOptions').innerHTML=choices.map(o=>`<label class="unit-option"><input type="radio" name="importUnit" value="${o.unit}" ${o.unit===suggestion?'checked':''}><span>按 ${unitName(o.unit)} 解释源坐标<strong>${o.dimensions.map(n=>fmt(n,6)).join(' × ')} <small>mm</small></strong></span></label>`).join('');
 $('busy').hidden=true;const dialog=$('unitDialog');dialog.showModal();return new Promise(resolve=>{dialog.addEventListener('close',()=>{const value=dialog.returnValue==='confirm'?document.querySelector('[name=importUnit]:checked').value:null;$('busy').hidden=false;resolve(value);},{once:true});});
}
async function importFiles(files){
 await withBusy('准备读取模型…',async()=>{
 const all=Array.from(files),primary=all.filter(f=>/\.(stl|obj|ply|glb|gltf)$/i.test(f.name));if(!primary.length)throw Error('请选择 STL、OBJ、PLY、GLB 或 GLTF 文件');
 const resources={};for(const f of all.filter(f=>/\.bin$/i.test(f.name))){if(f.size>256*1024*1024)throw Error('BIN 文件超过常规读取的 256 MB 预算，请转换为 STL / OBJ');resources[f.name]=await f.arrayBuffer();}
 let added=0;const failures=[];
 for(const file of primary){
  try{if(state.cards.length>=100)throw Error('计算记录已达 100 份，请先删除一些副本再导入');if(state.models.length>=12)throw Error('工作台最多 12 个模型，请备份后删除部分模型');
  const ext=file.name.split('.').pop().toLowerCase();let data;
  if(['stl','obj'].includes(ext))data=await startJob({type:'analyze',file,ext});
  else {if(file.size>256*1024*1024)throw Error('PLY / GLB / GLTF 常规读取上限 256 MB；请导出 STL / OBJ 使用高面数模式');const positions=await parseModel(await file.arrayBuffer(),ext,resources);data={positions,analysis:analyze(positions),previewOnly:false};}
  const {positions,analysis,previewOnly}=data;
  const unit=await chooseUnit(file.name,analysis.dimensions,ext);if(!unit)continue;
  const source=previewOnly?{size:file.size,name:file.name,fingerprint:await fingerprint(file)}:null;
  const m={id:crypto.randomUUID(),name:file.name,ext,positions,analysis,previewOnly,source,defaultUnit:unit};m.thumbnail=thumbnailFor(m);m.thumbnailVersion=2;state.models.push(m);if(previewOnly)sourceFiles.set(m.id,file);const card=makeCard(m);state.cards.push(card);state.selected=card.id;added++;
  }catch(e){if(e.message.includes('已取消')){if(added)update(true);throw e;}failures.push(file.name+'：'+e.message);}
 }
 update(true);$('propertiesBody').scrollTop=0;document.body.classList.remove('library-open');
 if(failures.length)toast(failures.join('；'));else if(added)toast('已导入 '+added+' 个模型 · 完整网格参与计算');
 });$('fileInput').value='';
}
function manualAnalysis(){return {volume:0,dimensions:[0,0,0],min:[0,0,0],max:[0,0,0],center:[0,0,0],triangles:0,valid:true,topologyChecked:true};}
function addManual(){if(state.cards.length>=100){toast('计算记录已达 100 份，请先删除一些副本');return;}let m=state.models.find(m=>m.manual);if(!m){if(state.models.length>=12){toast('请先删除一个模型，为体积计算记录留出位置');return;}m={id:crypto.randomUUID(),name:'手动体积',ext:'manual',manual:true,positions:new Float64Array(0),analysis:manualAnalysis(),defaultUnit:'mm'};state.models.push(m);}const c={...makeCard(m,false),name:'手动体积 '+(state.cards.filter(c=>c.modelId===m.id).length+1),manualVolume:null,volumeLocked:true};state.cards.push(c);state.selected=c.id;update();$('propertiesBody').scrollTop=0;document.body.classList.remove('library-open');}
function addDemo(kind='ring'){
 if(state.models.length>=12){toast('工作台最多 12 个模型');return;}
 const existing=state.models.find(m=>m.demo===kind);if(existing){const c=state.cards.find(c=>c.modelId===existing.id);selectCard(c.id);return;}
 if(state.cards.length>=100){toast('计算记录已达 100 份，请先删除一些副本');return;}
 let geometry;
 if(kind==='cube')geometry=new THREE.BoxGeometry(1,1,1);else{const points=[];for(let i=0;i<=64;i++){const a=i/64*Math.PI*2;points.push(new THREE.Vector2(10.45+Math.cos(a),3.5*Math.sin(a)));}geometry=new THREE.LatheGeometry(points,160);}
 const mesh=new THREE.Mesh(geometry),positions=flatten(mesh),analysis=analyze(positions);geometry.dispose();mesh.material.dispose();
 const m={id:crypto.randomUUID(),name:kind==='cube'?'校验方块 · 1 mm':'电影戒指比例示例 · 7 mm 宽',ext:'stl',positions,analysis,defaultUnit:'mm',demo:kind};m.thumbnail=thumbnailFor(m);m.thumbnailVersion=2;state.models.push(m);const c=makeCard(m);state.cards.push(c);state.selected=c.id;update(true);
}
function duplicate(id=state.selected){const c=state.cards.find(c=>c.id===id);if(!c)return;if(state.cards.length>=100){toast('最多保存 100 份记录');return;}const next=cloneCard(c);next.fees=(c.fees??[]).map(f=>({...f,id:crypto.randomUUID()}));if(modelFor(c).manual)next.volumeLocked=true;next.name=c.original?'尺寸方案 '+(state.cards.filter(x=>x.modelId===c.modelId&&!x.original).length+1).toString().padStart(2,'0'):c.name+' 副本';state.cards.push(next);state.selected=next.id;update(true);if(modelFor(next).manual){$('volumeInput').scrollIntoView({block:'nearest',behavior:'smooth'});toast('已复制体积记录，解锁后可独立修改');}else{$('sizeDetails').open=true;$('sizeDetails').scrollIntoView({block:'nearest',behavior:'smooth'});toast('已创建独立副本，可以修改尺寸');}}
function deleteCard(id){const c=state.cards.find(c=>c.id===id);if(!c||(c.original&&!modelFor(c)?.manual))return;state.cards=state.cards.filter(x=>x.id!==id);if(modelFor(c)?.manual&&!state.cards.some(x=>x.modelId===c.modelId))state.models=state.models.filter(m=>m.id!==c.modelId);if(state.selected===id)state.selected=state.cards.find(x=>x.modelId===c.modelId)?.id||state.cards[0]?.id;update(true);toast('已删除计算副本');}
function download(data,name,type='application/octet-stream'){const blob=data instanceof Blob?data:new Blob([data],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function guarded(fn){return e=>{const c=selected(),before=c?structuredClone(c):null;try{fn(e);if(c){estimate(Math.max(modelFor(c).analysis.volume,1),UNITS[c.unit],c.scale,c.density,c.price);if(modelFor(c).manual&&c.manualVolume!==null)estimateVolume(c.manualVolume,c.density,c.price);}update();}catch(err){if(c&&before)Object.assign(c,before);toast(err.message);render();}};}
function showMarket(){
 const c=selected();if(!c)return;const h=history(c.metal),s=summary(h.rows);$('marketDescription').textContent=`${materials[c.metal].name} · ${activeCurrency} / 克 · ${state.histories[c.metal]?'用户导入数据':'离线快照，核对日期 2026-09-22'}`;
 $('marketStats').innerHTML=s?[['区间均价',s.mean],['区间最低',s.min],['区间最高',s.max]].map(([k,v])=>`<div><small>${k}</small><strong>${esc(money(v))}</strong></div>`).join(''):'<p>暂无已核实的近月行情。请填写当日单价，或导入近期 CSV。</p>';
 $('marketSource').innerHTML=`${esc(h.source)}${h.url?` · <a href="${esc(h.url)}" target="_blank" rel="noopener noreferrer">查看来源 ↗</a>`:''}<br>${s?`${s.start} — ${s.end}，${s.count} 个交易日；${esc(h.kind||'日价格算术均值')}。`:'铜期货报价通常为元/吨，换算为元/克需除以 1,000,000。'}<br>${state.histories[c.metal]?'数据由用户提供，未由交易所核验。':'查询窗口 2026-08-22 — 2026-09-21；仅统计实际返回数据，不填补缺失日期。'}<br>离线参考不代表当日成交价，采购前请更新单价。`;
 $('useMeanBtn').disabled=!s;const canvas=$('priceChart'),ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);
 if(s){const w=canvas.width,prices=h.rows.map(r=>toDisplayCurrency(r.price,activeCurrency)),min=Math.min(...prices),max=Math.max(...prices);ctx.strokeStyle='#383c44';ctx.lineWidth=1;for(let i=1;i<4;i++){ctx.beginPath();ctx.moveTo(18,i*35);ctx.lineTo(w-18,i*35);ctx.stroke();}ctx.beginPath();prices.forEach((price,i)=>{const x=18+i/(prices.length-1||1)*(w-36),y=18+(1-(price-min)/(max-min||1))*110;if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);});ctx.strokeStyle='#efac6c';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#969eaa';ctx.font='11px sans-serif';ctx.fillText(s.start,18,149);ctx.fillText(s.end,w-84,149);}
 if(!$('marketDialog').open)$('marketDialog').showModal();
}
function validateState(raw){
 if(raw.version!==1||!Array.isArray(raw.models)||!Array.isArray(raw.cards)||raw.models.length>12||raw.cards.length>100)throw Error('不是有效工作台备份');
 const models=raw.models.map(m=>{if(typeof m.id!=='string'||typeof m.name!=='string'||!['stl','obj','ply','gltf','glb','manual'].includes(m.ext)||!UNITS[m.defaultUnit]||!m.positions||m.positions.length>18000000)throw Error('备份模型资料无效');const positions=new Float64Array(m.positions);let analysis;
 if(m.manual){if(m.ext!=='manual'||positions.length)throw Error('手动记录含有不应存在的模型几何');analysis=manualAnalysis();}else if(m.previewOnly){if(!['stl','obj'].includes(m.ext)||!m.source||typeof m.source.fingerprint!=='string'||!Number.isSafeInteger(m.source.size)||positions.length%9||!positions.length||!positions.every(Number.isFinite))throw Error('高面数预览数据无效');analysis=validateSummary(m.analysis);if(positions.length/9>analysis.triangles)throw Error('预览面数超过模型面数');}
 else analysis=analyze(positions);
 return {...m,name:m.name.slice(0,200),positions,analysis,thumbnail:safeThumbnail(m.thumbnail)};});
 const ids=new Set(models.map(m=>m.id));if(ids.size!==models.length)throw Error('备份模型编号重复');
 const cards=raw.cards.map(c=>{if(!ids.has(c.modelId)||typeof c.id!=='string'||typeof c.name!=='string'||!Object.hasOwn(materials,c.metal)||!Object.hasOwn(UNITS,c.unit)||typeof c.original!=='boolean')throw Error('备份记录无效');estimate(1,UNITS[c.unit],c.scale,c.density,c.price);if(models.find(m=>m.id===c.modelId).manual){if(c.manualVolume!==null)estimateVolume(c.manualVolume,c.density,c.price);if(typeof c.volumeLocked!=='boolean')throw Error('手动体积锁定状态无效');}if(c.original&&c.scale.some(v=>v!==1))throw Error('原始记录的比例无效');const allowance=c.feedAllowancePercent??null,quantity=c.batchQuantity??1,basis=c.priceBasis??'unconfirmed';if(allowance!==null&&(!Number.isFinite(allowance)||allowance<0||allowance>500)||!Number.isInteger(quantity)||quantity<1||quantity>100000||!['unconfirmed','reference','supplier'].includes(basis)||!['net','feed'].includes(c.materialBasis??'net'))throw Error('报价记录无效');return {...c,fees:validateFees(c.fees),name:c.name.slice(0,80),priceOrigin:String(c.priceOrigin||'备份单价').slice(0,250),feedAllowancePercent:allowance,batchQuantity:quantity,materialBasis:c.materialBasis??'net',priceBasis:basis,supplierName:String(c.supplierName??'').slice(0,80),quoteDate:String(c.quoteDate??'').slice(0,10),validUntil:String(c.validUntil??'').slice(0,10),processTemplate:processTemplates.some(t=>t.id===c.processTemplate)?c.processTemplate:''};});
 if(new Set(cards.map(c=>c.id)).size!==cards.length||models.some(m=>m.manual?!cards.some(c=>c.modelId===m.id):cards.filter(c=>c.modelId===m.id&&c.original).length!==1))throw Error('每个模型必须有且只有一份原始记录');
 const histories={};for(const [key,h]of Object.entries(raw.histories||{})){if(!Object.hasOwn(materials,key)||!Array.isArray(h.rows)||h.rows.length>31)throw Error('行情备份无效');for(const r of h.rows){if(!/^\d{4}-\d{2}-\d{2}$/.test(r.date))throw Error('行情日期无效');positive(r.price,'行情单价');}histories[key]={rows:h.rows,source:'用户导入行情（来自工作台备份）',kind:'已导入日价格算术均值'};}
 return {version:1,models,cards,histories,selected:cards.some(c=>c.id===raw.selected)?raw.selected:cards[0]?.id??null};
}

$('manualBtn').onclick=addManual;
$('volumeLock').onclick=()=>{const c=selected();if(!modelFor(c)?.manual)return;c.volumeLocked=!c.volumeLocked;update();if(!c.volumeLocked)$('volumeInput').focus();};
$('focusVolumeBtn').onclick=()=>{const c=selected();if(!modelFor(c)?.manual)return;c.volumeLocked=false;update();$('volumeInput').scrollIntoView({block:'center',behavior:'smooth'});$('volumeInput').focus();};
$('volumeInput').onchange=guarded(()=>{const c=selected();if(!modelFor(c)?.manual||c.volumeLocked)return;c.manualVolume=$('volumeInput').value===''?null:positive(Number($('volumeInput').value),'体积');});
$('importBtn').onclick=$('dropBtn').onclick=()=>$('fileInput').click();$('fileInput').onchange=e=>importFiles(e.target.files);
document.addEventListener('dragover',e=>{e.preventDefault();if(!busy)document.body.classList.add('dragging');});document.addEventListener('dragleave',e=>{if(!e.relatedTarget)document.body.classList.remove('dragging');});document.addEventListener('drop',e=>{e.preventDefault();document.body.classList.remove('dragging');if(!busy)importFiles(e.dataTransfer.files);});
$('demoBtn').onclick=()=>addDemo();$('cubeBtn').onclick=()=>addDemo('cube');$('copyBtn').onclick=$('addCardBtn').onclick=()=>duplicate();
$('feeKind').innerHTML=feeCatalog.map(f=>`<option value="${f.kind}">${f.name}</option>`).join('');
$('processTemplate').innerHTML+=processTemplates.map(t=>`<option value="${t.id}">${t.name}</option>`).join('');
$('applyTemplateBtn').onclick=()=>{const c=selected(),id=$('processTemplate').value;if(!c||!id){toast('请先选择工艺模板');return;}try{c.fees=applyProcessTemplate(c.fees??[],id);c.processTemplate=id;update();$('costPanel').open=true;$('feeDetailsSection').open=true;toast('已替换为所选模板项目；请填写实际工艺报价');}catch(e){toast(e.message);}};
$('feedAllowance').onchange=guarded(()=>{const raw=$('feedAllowance').value,n=raw===''?null:Number(raw);if(n!==null&&(!Number.isFinite(n)||n<0||n>500))throw Error('投料余量须在 0% 至 500% 之间');selected().feedAllowancePercent=n;});
$('materialBasis').onchange=guarded(()=>{selected().materialBasis=$('materialBasis').value;});
$('batchQuantity').onchange=guarded(()=>{const n=Number($('batchQuantity').value);if(!Number.isInteger(n)||n<1||n>100000)throw Error('制作数量须为 1 至 100000 件');selected().batchQuantity=n;});
$('priceBasis').onchange=guarded(()=>{selected().priceBasis=$('priceBasis').value;});
for(const id of ['supplierName','quoteDate','validUntil'])$(id).onchange=guarded(()=>{selected()[id]=$(id).value.trim();});
$('addFeeBtn').onclick=()=>{const c=selected();if(!c)return;if((c.fees??[]).length>=30){toast('每份记录最多添加 30 项费用');return;}c.fees??=[];c.fees.push(makeFee($('feeKind').value));update();$('costPanel').open=true;$('feeDetailsSection').open=true;};
$('feeList').onclick=e=>{const b=e.target.closest('[data-remove-fee]');if(!b)return;const c=selected();c.fees=c.fees.filter(f=>f.id!==b.dataset.removeFee);update();};
 $('feeList').onchange=guarded(e=>{const field=e.target.dataset.feeField;if(!field)return;const row=e.target.closest('[data-fee-id]'),fee=(selected().fees??[]).find(f=>f.id===row?.dataset.feeId);if(!fee)return;if(field==='name')fee.name=e.target.value.trim();else if(field==='mode')fee.mode=e.target.value;else if(field==='rate'){const raw=e.target.value;fee.rate=raw===''?null:toCanonicalCny(Number(raw),activeCurrency);}else if(field==='quantity')fee.quantity=Number(e.target.value);selected().fees=validateFees(selected().fees);});
let pendingDeleteModelId=null;$('confirmDeleteModelBtn').onclick=()=>{const id=pendingDeleteModelId;if(!id)return;pendingDeleteModelId=null;$('deleteModelDialog').close();sourceFiles.delete(id);collapsedModels.delete(id);state.models=state.models.filter(m=>m.id!==id);state.cards=state.cards.filter(c=>c.modelId!==id);if(!selected())state.selected=state.cards[0]?.id??null;update(true);};$('modelList').onclick=e=>{const toggle=e.target.closest('[data-toggle-model]');if(toggle){const id=toggle.dataset.toggleModel;if(collapsedModels.has(id))collapsedModels.delete(id);else collapsedModels.add(id);render();return;}const rem=e.target.closest('[data-remove-model]');if(rem){const m=state.models.find(x=>x.id===rem.dataset.removeModel);if(!m)return;pendingDeleteModelId=m.id;$('deleteModelName').textContent=`删除「${m.name}」和它的全部计算记录？原文件不受影响。`;$('deleteModelDialog').showModal();return;}const record=e.target.closest('[data-select-card]');if(record){selectCard(record.dataset.selectCard);return;}const b=e.target.closest('[data-model]');if(b){const c=state.cards.find(c=>c.modelId===b.dataset.model);selectCard(c.id);}};
$('cardList').onclick=e=>{const dup=e.target.closest('[data-duplicate]'),del=e.target.closest('[data-delete]'),card=e.target.closest('[data-card]');if(dup)duplicate(dup.dataset.duplicate);else if(del)deleteCard(del.dataset.delete);else if(card)selectCard(card.dataset.card);};$('cardList').onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-card]')){e.preventDefault();selectCard(e.target.dataset.card);}};
$('cardName').onchange=guarded(()=>{selected().name=$('cardName').value.trim()||'未命名记录';});
$('unit').onchange=guarded(()=>{selected().unit=$('unit').value;viewer?.setModel(modelFor(),selected().scale.map(n=>n*UNITS[selected().unit]),materials[selected().metal].color);viewer?.fit();});
['dimX','dimY','dimZ'].forEach((id,i)=>{$(id).onchange=guarded(()=>{const c=selected(),m=modelFor(c);if(c.original)return;const value=lengthToMillimeters(positive(Number($(id).value),'尺寸'),displayUnit),old=m.analysis.dimensions[i]*UNITS[c.unit]*c.scale[i],ratio=value/old;if($('lockRatio').checked)c.scale=c.scale.map(v=>v*ratio);else c.scale[i]=value/(m.analysis.dimensions[i]*UNITS[c.unit]);estimate(Math.max(m.analysis.volume,1),UNITS[c.unit],c.scale,c.density,c.price);});});
$('scalePercent').onchange=guarded(()=>{const c=selected();if(c.original)return;const n=positive(Number($('scalePercent').value),'比例')/100;c.scale=[n,n,n];});
function selectMetal(key){const c=selected();if(!c||!Object.hasOwn(materials,key))return;c.metal=key;c.density=materials[key].density;c.price=defaultPrice(key);c.priceOrigin=origin(key);c.priceBasis='unconfirmed';update();}
$('metalTabs').onclick=e=>{const b=e.target.closest('[data-metal]');if(b)selectMetal(b.dataset.metal);};
$('otherMetalsBtn').onclick=()=>{$('otherMetalsList').innerHTML=otherMetalKeys.map(key=>`<button type="button" data-other-metal="${key}"><strong>${esc(materials[key].symbol)}</strong><span>${esc(language.translate(materials[key].name))}</span><small>${materials[key].density} g/cm³</small></button>`).join('');$('otherMetalsDialog').showModal();};
$('otherMetalsList').onclick=e=>{const b=e.target.closest('[data-other-metal]');if(!b)return;selectMetal(b.dataset.otherMetal);$('otherMetalsDialog').close();};
$('density').onchange=guarded(()=>{selected().density=positive(Number($('density').value),'密度');});$('price').onchange=guarded(()=>{const raw=$('price').value,n=raw===''?null:Number(raw);if(n!==null&&(!Number.isFinite(n)||n<0))throw Error('单价必须是大于等于 0 的数字');selected().price=n===null?null:toCanonicalCny(n,activeCurrency);selected().priceOrigin=n===null?'手动单价（未填写）':`手动单价 · ${new Date().toLocaleDateString('sv-SE')} · ${activeCurrency}`;selected().priceBasis='unconfirmed';});
$('solidBtn').onclick=()=>{viewer?.setWire(false);$('solidBtn').classList.add('selected');$('wireBtn').classList.remove('selected');};$('wireBtn').onclick=()=>{viewer?.setWire(true);$('wireBtn').classList.add('selected');$('solidBtn').classList.remove('selected');};$('gridBtn').onclick=()=>{$('gridBtn').setAttribute('aria-pressed',String(viewer?.toggleGrid()));};$('fitBtn').onclick=()=>viewer?.fit();$('viewSelect').onchange=()=>{$('viewSelect').value==='iso'?viewer?.fit('iso'):viewer?.setAxisView($('viewSelect').value);};$('projectionBtn').onclick=()=>{const orthographic=viewer?.toggleProjection();$('projectionBtn').textContent=orthographic?'正交':'透视';$('projectionBtn').setAttribute('aria-pressed',String(orthographic));};document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&!e.altKey){if(e.key.toLowerCase()==='s'){e.preventDefault();$(e.shiftKey?'saveAsBtn':'backupBtn').click();return;}if(!e.shiftKey&&e.key.toLowerCase()==='o'){e.preventDefault();$('restoreBtn').click();return;}}if(e.key.toLowerCase()==='f'&&!/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)&&!document.querySelector('dialog[open]'))viewer?.fit();});
let pendingExport=null;
function updateExportPreview(){const pending=pendingExport,c=pending&&state.cards.find(x=>x.id===pending.cardId),m=c&&modelFor(c),unit=$('exportUnitSelect').value;if(!m)return;$('exportDimensionsPreview').textContent=`输出尺寸约为 ${m.analysis.dimensions.map((n,i)=>fmt(lengthFromMillimeters(n*UNITS[c.unit]*c.scale[i],unit),5)).join(' × ')} ${unit}。模型几何不变，仅转换输出坐标。`;}
$('exportBtn').onclick=()=>{const c=selected(),m=modelFor(c),ext=$('exportFormat').value;if(!m||m.manual)return;pendingExport={cardId:c.id,ext};$('exportUnitSelect').value=displayUnit==='m'?'mm':displayUnit;updateExportPreview();$('exportUnitDialog').showModal();};
$('exportUnitSelect').onchange=updateExportPreview;
$('exportUnitDialog').addEventListener('close',()=>{if($('exportUnitDialog').returnValue!=='confirm'||!pendingExport)return;const pending=pendingExport;pendingExport=null;performExport(pending,$('exportUnitSelect').value);});
async function performExport(pending,unit){
 const c=state.cards.find(x=>x.id===pending.cardId),m=c&&modelFor(c),ext=pending.ext;if(!m||m.manual)return;
 const safe=s=>String(s).replace(/[<>:"/\|?*\x00-\x1f]/g,'_').trim().slice(0,100)||'model',factors=c.scale.map(n=>n*UNITS[c.unit]/UNITS[unit]),name=m.name.replace(/\.(stl|obj|ply|glb|gltf)$/i,'')+'_'+safe(c.name)+'_'+unit+'.'+ext;
 let handle=null;if(m.previewOnly){if(!sourceFiles.has(m.id)){toast('请先重新选择原模型文件，再导出完整模型');$('relinkInput').click();return;}if(typeof showSaveFilePicker==='function'){try{handle=await showSaveFilePicker({suggestedName:name});}catch(e){if(e.name!=='AbortError')toast(e.message);return;}}else if(m.analysis.triangles*(ext==='stl'?50:400)>200*1024*1024){toast('此大模型导出需要桌面 Chrome / Edge 的文件写入功能。计算结果已保留。');return;}}
 await withBusy('正在导出完整模型…',async()=>{let data;if(m.previewOnly)data=await exportLarge({file:sourceFiles.get(m.id),model:m,targetExt:ext,factors,unit,handle,progress,taskHook:job=>{activeJob=job;$('cancelBtn').disabled=false;}});else data=exportModel(m.positions,factors,ext,unit);if(data)download(data,name);toast(`已导出完整模型 · 单位 ${unit}`);});
}
$('cancelBtn').onclick=()=>activeJob?.cancel();
$('resetWorkspaceBtn').onclick=()=>{if(confirm('将当前显示的工作台保存为新的工作台？这会替换无法恢复的旧记录。')){persistenceBlocked=false;$('resetWorkspaceBtn').hidden=true;save();}};
$('libraryToggle').onclick=()=>{$('libraryPanel').open=!$('libraryPanel').open;};$('libraryPanel').ontoggle=()=>{$('libraryToggle').setAttribute('aria-expanded',String($('libraryPanel').open));};
$('relinkBtn').onclick=()=>$('relinkInput').click();
$('previewUpgrade').onclick=()=>$('relinkInput').click();
$('relinkInput').onchange=async e=>{const file=e.target.files[0],m=modelFor();if(!file||!m?.previewOnly)return;await withBusy('核对原模型文件…',async()=>{if(file.size!==m.source.size||await fingerprint(file)!==m.source.fingerprint)throw Error('所选文件与计算时的原文件不匹配');const r=await startJob({type:'analyze',file,ext:m.ext});if(r.analysis.triangles!==m.analysis.triangles||Math.abs(r.analysis.volume-m.analysis.volume)>Math.max(1e-8,m.analysis.volume*1e-10))throw Error('重新计算结果与记录不同，请重新导入该模型');sourceFiles.set(m.id,file);if(r.positions.length/9===m.analysis.triangles)m.positions=r.positions;update(true);toast('原文件已重新关联；完整表面预览已更新');});$('relinkInput').value='';};
$('helpBtn').onclick=()=>$('helpDialog').showModal();$('authorBtn').onclick=()=>$('aboutDialog').showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());$('marketBtn').onclick=showMarket;
$('useMeanBtn').onclick=()=>{const c=selected(),s=summary(history(c.metal).rows);if(!s)return;c.price=s.mean;c.priceOrigin=origin(c.metal);c.priceBasis='reference';$('marketDialog').close();update();toast('已应用区间均价，仅更新当前记录');};$('importHistoryBtn').onclick=()=>$('historyInput').click();$('historyInput').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>1024*1024)throw Error('CSV 文件上限 1 MB');const rows=parseHistory(await file.text());state.histories[selected().metal]={rows,source:`用户导入：${file.name.slice(0,100)}`,kind:'日价格算术均值'};save();showMarket();toast('行情已载入，点击「使用区间均价」应用');}catch(e){toast(e.message);}finally{$('historyInput').value='';}};
function loadProject(contents,confirmReplace=true){const next=validateState(parseProject(contents));if(confirmReplace&&state.models.length&&!confirm('用所选文件替换当前工作台？请先保存需要保留的记录。'))return false;sourceFiles.clear();state=next;persistenceBlocked=false;$('resetWorkspaceBtn').hidden=true;update(true);if($('aboutDialog').open)$('aboutDialog').close();toast('工程文件已打开');return true;}
async function saveWorkspaceFile(saveAs=false){await withBusy(saveAs?'正在另存工程文件…':'正在保存工程文件…',async()=>{const contents=serializeProject(state);if(window.metalLabDesktop){const saved=await (saveAs?window.metalLabDesktop.saveProjectAs(contents):window.metalLabDesktop.saveProject(contents));if(!saved)return;await refreshRecentProjects();toast(`已保存：${saved.name}`);}else{const stem=browserProjectStem||`金属工坊工程_${new Date().toLocaleDateString('sv-SE')}`,suffix=saveAs?`_${String(++browserSaveSequence).padStart(3,'0')}`:'';download(contents,`${stem}${suffix}.mlab`,'application/x-metal-lab-project');toast('工程文件已下载为 .mlab；请妥善保管');}});}
$('backupBtn').onclick=()=>saveWorkspaceFile();$('saveAsBtn').onclick=()=>saveWorkspaceFile(true);
$('restoreBtn').onclick=async()=>{if(window.metalLabDesktop){await withBusy('正在打开工程文件…',async()=>{const opened=await window.metalLabDesktop.openProject();if(opened&&loadProject(opened.contents))await refreshRecentProjects();});}else $('restoreInput').click();};
$('restoreInput').onchange=async e=>{const file=e.target.files[0];if(!file)return;await withBusy('正在检查工程文件…',async()=>{if(loadProject(await file.text())){browserProjectStem=file.name.replace(/\.(mlab|json)$/i,'').replace(/_\d{3,}$/,'');browserSaveSequence=Number(file.name.match(/_(\d{3,})\.mlab$/i)?.[1]||0);}});$('restoreInput').value='';};
async function refreshRecentProjects(){if(!window.metalLabDesktop)return;const files=await window.metalLabDesktop.recentProjects();$('recentProjectList').innerHTML=files.length?files.map(file=>`<button class="recent-project" data-recent-path="${esc(file.path)}">${esc(file.name)}<small>${esc(file.path)}</small></button>`).join(''):'<p class="hint">还没有最近打开的工程文件。</p>';}
$('desktopOpenProjectBtn').onclick=()=>$('restoreBtn').click();
$('recentProjectList').onclick=async e=>{const button=e.target.closest('[data-recent-path]');if(!button||!window.metalLabDesktop)return;await withBusy('正在打开最近的工程…',async()=>{const opened=await window.metalLabDesktop.openRecent(button.dataset.recentPath);if(loadProject(opened.contents)){$('aboutDialog').close();await refreshRecentProjects();}});};
function sheetSelection(){return [...$('sampleSheetOptions').querySelectorAll('input:checked')].map(input=>{const card=state.cards.find(c=>c.id===input.value);return card?{card,model:modelFor(card)}:null;}).filter(Boolean);}
function updateSheetDialog(){const count=sheetSelection().length,format=$('sheetFormat').value;$('exportSampleBtn').disabled=!count;$('sheetFormatHint').textContent=!count?'请至少勾选一份记录。':format==='pdf'?`${count} 份记录将合并成一个 PDF，每份一页。`:count===1?'将导出一张 JPG 图片。':`${count} 张 JPG 图片将放在一个 ZIP 文件中。`;}
$('sheetBtn').onclick=()=>{if(!state.cards.length){toast('请先创建计算记录');return;}$('sampleSheetOptions').innerHTML=state.cards.map(card=>{const model=modelFor(card);return `<label class="sheet-option"><input type="checkbox" value="${esc(card.id)}" ${card.id===state.selected?'checked':''}><span>${esc(card.name)}<small>${esc(model?.name??'')} · ${result(card)?fmt(result(card).mass)+' g':'待核对'}</small></span></label>`;}).join('');$('sheetFormat').value=matchMedia('(max-width:600px)').matches||navigator.maxTouchPoints>0?'jpg':'pdf';updateSheetDialog();$('sampleSheetDialog').showModal();};
$('sampleSheetOptions').onchange=updateSheetDialog;$('sheetFormat').onchange=updateSheetDialog;
$('selectAllSheetsBtn').onclick=()=>{const boxes=[...$('sampleSheetOptions').querySelectorAll('input')],all=boxes.every(box=>box.checked);for(const box of boxes)box.checked=!all;updateSheetDialog();};
$('exportSampleBtn').onclick=async()=>{const entries=sheetSelection(),format=$('sheetFormat').value;if(!entries.length){toast('请至少勾选一份记录');return;}$('sampleSheetDialog').close();await withBusy('正在生成打样单…',async()=>{const date=new Date().toLocaleDateString('sv-SE'),onProgress=(done,total)=>progress(done/total,`正在生成第 ${done} / ${total} 份打样单…`),name=sampleSheetFileName(entries,date,format,language.locale);if(format==='pdf'){download(await buildSampleSheetBatchPdf(entries,onProgress,language.locale,activeCurrency,displayUnit),name);}else{const pages=await buildSampleSheetJpegs(entries,onProgress,language.locale,activeCurrency,displayUnit);if(pages.length===1)download(new Blob([pages[0].jpeg],{type:'image/jpeg'}),name);else{const files=pages.map((page,i)=>({name:`${String(i+1).padStart(2,'0')}_${sampleSheetFileName([entries[i]],date,'jpg',language.locale)}`,data:page.jpeg}));download(new Blob([zipFiles(files)],{type:'application/zip'}),name);}}toast(`${entries.length} 份打样单已导出，请核对待确认项目`);});};

async function init(){
 try{viewer=createViewer($('viewport'));viewer.start();}catch(e){$('viewportError').hidden=false;$('viewportError').textContent='无法启用 3D 预览。请使用支持 WebGL 的 Edge / Chrome 并开启硬件加速。计算与导出仍然可用。';}
 try{const stored=await readWorkspace();if(stored){state=validateState(stored);let refreshedThumbnail=false;for(const model of state.models){if(!model.manual&&model.thumbnailVersion!==2){const thumbnail=thumbnailFor(model);if(thumbnail){model.thumbnail=thumbnail;model.thumbnailVersion=2;refreshedThumbnail=true;}}}const removedLegacyCube=removeUntouchedLegacyCube(state);render();viewer?.fit();if(refreshedThumbnail||removedLegacyCube)save();else $('saveStatus').textContent='已恢复本地工作台';return;}}catch{persistenceBlocked=true;$('resetWorkspaceBtn').hidden=false;toast('未能恢复本地记录。已暂停自动保存，原数据不会被示例覆盖；可打开文件。');}
 render();
}
const language=initLanguage();activeLocale=language.locale;
try{const savedUnit=localStorage.getItem('metal-lab-display-unit');if(displayUnits.some(v=>v.code===savedUnit))displayUnit=savedUnit;}catch{}
try{const savedCurrency=localStorage.getItem('metal-lab-currency');if(currencies.some(v=>v.code===savedCurrency))activeCurrency=savedCurrency;else activeCurrency=defaultCurrencyForLocale(activeLocale);}catch{activeCurrency=defaultCurrencyForLocale(activeLocale);}
function renderCurrencyOptions(){$('currencySelect').innerHTML=currencies.map(v=>`<option value="${v.code}">${esc(language.translate(`${v.code} · ${v.name}`))}</option>`).join('');$('currencySelect').value=activeCurrency;$('currencyRateHint').textContent=language.translate(`汇率快照：${CURRENCY_SNAPSHOT_DATE} ECB 参考汇率。离线换算仅供估算。`);}
$('displayUnitSelect').value=displayUnit;renderCurrencyOptions();
$('languageSelect').addEventListener('change',()=>{activeLocale=language.locale;activeCurrency=defaultCurrencyForLocale(activeLocale);renderCurrencyOptions();try{localStorage.setItem('metal-lab-currency',activeCurrency);}catch{}render();});
$('currencySelect').addEventListener('change',()=>{activeCurrency=$('currencySelect').value;try{localStorage.setItem('metal-lab-currency',activeCurrency);}catch{}render();});
$('displayUnitSelect').addEventListener('change',()=>{displayUnit=$('displayUnitSelect').value;try{localStorage.setItem('metal-lab-display-unit',displayUnit);}catch{}render();});
init().then(async()=>{const desktop=window.metalLabDesktop;if(!desktop)return;$('desktopRecent').hidden=false;desktop.onOpenProject(async project=>{try{loadProject(project.contents,false);await refreshRecentProjects();}catch(error){toast(error.message);}});try{const startup=await desktop.startupProject();if(startup)loadProject(startup.contents,false);await refreshRecentProjects();}catch(error){toast(`打开工程失败：${error.message}`);}if(!$('aboutDialog').open)$('aboutDialog').showModal();}).catch(error=>toast(error.message));

