const rows=[
 ["模型预览、计算记录和手动单价自动保存在当前浏览器。高面数模型仅保存预览和完整计算结果，不把数 GB 原文件复制进浏览器；重新打开后导出需要再次选择原文件。高面数导出读取完整原文件，不会把抽样预览当作原模型。换浏览器、移动 HTML 文件或清理浏览数据可能丢失记录，可从「更多」保存 .mlab 工程文件，日常分享请用「导出打样单」。金、银、铂、钯的参考行情在启动及每五分钟联网刷新，采用前核对来源与行情时间；不会自动覆盖手动采购报价。铜、铝、锡及合金等使用手动采购报价。历史快照和 CSV 仅作为历史参考，汇率为每日参考数据。制作费用可按克、按件、按数量和材料费比例叠加，并随记录独立保存；报价需自行填写。", "Previews, calculations and manual quotes save locally. Large models retain previews and full analysis; reselect the original file to export after reopening. Back up .mlab projects and original models. Gold, silver, platinum and palladium references refresh online on startup and every five minutes. Apply a reference explicitly to the current record; refresh never overwrites quotes. Copper, aluminum, tin and alloys use manual purchase quotes. Historical snapshots and CSV are historical references; FX updates daily. Making fees can combine weight, item, quantity and material percentages per calculation.", "プレビュー、計算記録、手入力見積はローカル保存します。大きなモデルはプレビューと全体の計算結果を保存し、再起動後の完全出力には元ファイルを再選択します。.mlab 工程と元モデルをバックアップしてください。金、銀、プラチナ、パラジウムの参考相場は起動時と5分ごとに更新します。適用は現在の記録だけを変更し、更新で見積を上書きしません。銅、アルミ、錫、合金等は手入力します。過去のスナップショットと CSV は過去の参考資料で、為替は日次参考です。加工費は重量、個数、数量、材料費割合で組み合わせ、記録ごとに保存します。", "미리보기, 계산 기록과 직접 입력한 견적은 로컬에 저장됩니다. 큰 모델은 미리보기와 전체 분석 결과를 저장하며 다시 연 후 전체 모델을 내보내려면 원본 파일을 다시 선택합니다. .mlab 프로젝트와 원본 모델을 백업하세요. 금, 은, 백금, 팔라듐 참고 시세는 시작 시와 5분마다 갱신됩니다. 참고 가격은 현재 기록에 직접 적용하며 갱신은 견적을 덮어쓰지 않습니다. 구리, 알루미늄, 주석, 합금 등은 직접 입력합니다. 과거 스냅샷과 CSV는 과거 참고 자료이며 환율은 일일 참고 데이터입니다. 가공비는 무게, 개수, 수량과 재료비 비율로 합산하여 기록별로 저장합니다."],
 ['自动参考行情','Automatic reference prices','自動参考相場','자동 참고 시세'],
 ['立即更新','Refresh now','今すぐ更新','지금 갱신'],
 ['采用最新参考价','Apply latest reference','最新参考価格を適用','최신 참고 가격 적용'],
 ['手动采购报价','Manual purchase quote','仕入見積を手入力','구매 견적 직접 입력'],
 ['当前计价单价','Current calculation rate','現在の計算単価','현재 계산 단가'],
 ['参考行情','Reference price','参考相場','참고 시세'],
 ['行情时间','Price timestamp','相場日時','시세 시간'],
 ['来源','Source','情報源','출처'],
 ['每日参考汇率','Daily reference FX','日次参考為替','일일 참고 환율'],
 ['参考汇率仅用于估算，不是实时成交汇率。','Reference FX is for estimates, not live transaction rates.','参考為替は概算用で、リアルタイムの取引レートではありません。','참고 환율은 추정용이며 실시간 거래 환율이 아닙니다.'],
 ['汇率日期','FX date','為替基準日','환율 날짜'],
 ['正在更新参考行情…','Updating reference prices…','参考相場を更新中…','참고 시세 갱신 중…'],
 ['自动更新已关闭','Automatic updates disabled','自動更新はオフです','자동 갱신 꺼짐'],
 ['联网自动更新参考行情','Update reference prices online','参考相場をオンラインで自動更新','온라인 참고 시세 자동 갱신'],
 ['启动及每 5 分钟刷新；报价需点击采用，手动报价不会自动覆盖。','Refresh on startup and every 5 minutes. Apply a reference explicitly; manual quotes stay unchanged.','起動時と5分ごとに更新。参考価格は適用操作が必要で、手入力の見積は上書きしません。','시작 시와 5분마다 갱신합니다. 참고 가격은 적용해야 하며 직접 입력한 견적은 덮어쓰지 않습니다.'],
 ['暂无自动行情，请填写采购报价。','No automatic feed for this metal. Enter a purchase quote.','この金属の自動相場はありません。仕入見積を入力してください。','이 금속은 자동 시세를 제공하지 않습니다. 구매 견적을 입력하세요.'],
 ['尚未取得参考行情。','Reference price not available yet.','参考相場はまだ取得されていません。','아직 참고 시세를 가져오지 못했습니다.'],
 ['数据来自缓存，请核对行情时间。','Cached data. Check the price timestamp.','キャッシュのデータです。相場日時を確認してください。','캐시 데이터입니다. 시세 시간을 확인하세요.'],
 ['本次更新失败，保留上次数据。','Update failed; previous data retained.','更新に失敗しました。前回のデータを保持しています。','갱신에 실패하여 이전 데이터를 유지합니다.'],
 ['行情已过期或汇率不可用，请更新后再采用。','Price is stale or FX is unavailable. Refresh before applying.','相場が古いか為替が利用できません。更新後に適用してください。','시세가 오래되었거나 환율을 사용할 수 없습니다. 갱신 후 적용하세요.'],
 ['已获取参考行情，仅供估算。','Reference price fetched; for estimates only.','参考相場を取得しました。概算専用です。','참고 시세를 가져왔습니다. 추정용입니다.'],
 ['参考行情不包含采购溢价、税费及工艺费；铜、铝、锡及合金等使用手动报价。','References exclude purchase premiums, taxes and making fees. Copper, aluminum, tin and alloys use manual quotes.','参考相場に仕入上乗せ、税金、加工費は含みません。銅、アルミ、錫、合金等は手入力します。','참고 시세에는 구매 할증, 세금, 가공비가 포함되지 않습니다. 구리, 알루미늄, 주석, 합금 등은 직접 입력합니다.'],
 ['已采用参考价，仅更新当前记录。','Reference applied to this calculation only.','現在の記録だけに参考価格を適用しました。','현재 기록에만 참고 가격을 적용했습니다.'],
 ['参考价资料已保存；采购前请确认实际报价。','Reference details saved. Confirm the purchase quote before ordering.','参考価格の情報を保存しました。購入前に実際の見積を確認してください。','참고 가격 정보를 저장했습니다. 구매 전 실제 견적을 확인하세요.'],
 ['采用参考价','Use reference price','参考価格を使用','참고 가격 사용'],
 ['参考价','Reference price','参考価格','참고 가격'],
 ['内置汇率快照','Built-in FX snapshot','内蔵為替スナップショット','내장 환율 스냅샷'],
 ['汇率更新失败，保留已有汇率。','FX update failed; previous rates retained.','為替更新に失敗しました。既存の為替を保持します。','환율 갱신에 실패하여 기존 환율을 유지합니다.'],
 ['正在编辑或导出，汇率稍后应用。','Editing or exporting; FX will be applied afterward.','編集中または出力中のため、為替は後で適用します。','편집 또는 내보내기 중입니다. 환율은 이후 적용됩니다.'],
 ['自动行情仅覆盖金、银、铂、钯。','Automatic feeds cover gold, silver, platinum and palladium only.','自動相場は金、銀、プラチナ、パラジウムのみです。','자동 시세는 금, 은, 백금, 팔라듐만 지원합니다.'],
];
export const marketStrings=Object.fromEntries(rows.map(([cn,en,ja,ko])=>[cn,{en,ja,ko}]));
export function translateMarket(text,locale){return marketStrings[text]?.[locale];}
